name: kibana
type: nodejs:10
disk: 128
hooks:
  build: |
    source .environment
    echo $VERSION
    wget https://artifacts.elastic.co/downloads/kibana/kibana-7.2.1-linux-x86_64.tar.gz
    tar xzvf kibana-7.2.1-linux-x86_64.tar.gz
    mkdir init/
    mv kibana-7.2.1-linux-x86_64/optimize/bundles init/
  deploy: |
    mv init/bundles kibana-7.2.1-linux-x86_64/optimize/

relationships:
  elasticsearch: elastic:elasticsearch

web:
  commands:
    start: |
      cd kibana-7.2.1-linux-x86_64 
      bin/kibana -p $PORT

mounts:
  "kibana-7.2.1-linux-x86_64/optimize": "shared:files/optimize"