name: kibana
type: nodejs:10
disk: 4096
hooks:
  build: |
    echo "echoing version:" $VERSION
    echo "echoing platform cache dir:" $PLATFORM_CACHE_DIR
    wget https://artifacts.elastic.co/downloads/kibana/kibana-7.2.1-linux-x86_64.tar.gz
    tar xzvf kibana-7.2.1-linux-x86_64.tar.gz -C $PLATFORM_CACHE_DIR
    cp -r $PLATFORM_CACHE_DIR/kibana-7.2.1-linux-x86_64 $PLATFORM_APP_DIR/
    mv kibana.yml kibana-7.2.1-linux-x86_64/config/

relationships:
  elasticsearch: elastic:elasticsearch

web:
  commands:
    start: |
      cd kibana-7.2.1-linux-x86_64 
      bin/kibana

mounts:
  "kibana-7.2.1-linux-x86_64/optimize": "shared:files/optimize"
  "kibana-7.2.1-linux-x86_64/data": "shared:files/data"