name: kibana
type: nodejs:10
disk: 128
hooks:
  build: |
    echo $VERSION
    wget https://artifacts.elastic.co/downloads/kibana/kibana-7.2.1-linux-x86_64.tar.gz
    tar xzvf kibana-7.2.1-linux-x86_64.tar.gz
    mv kibana.yml kibana-7.2.1-linux-x86_64/config/

relationships:
  elasticsearch: elastic:elasticsearch

web:
  commands:
    start: |
      cd kibana-7.2.1-linux-x86_64 

mounts:
  "kibana-7.2.1-linux-x86_64/optimize": "shared:files/optimize"
  "kibana-7.2.1-linux-x86_64/data": "shared:files/data"