https://{default}:
  type: upstream
  upstream: kibana:http

https://es.{default}:
  type: upstream
  upstream: elastic_test:elasticsearch
  tls:
    client_authentication: "require"
    client_certificate_authorities:
      - !include
        type: string
        path: rootCA.crt
